org: freyrsunset
app: fishie
service: fishie
frameworkVersion: "4"
useDotenv: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.12
  environment:
    IG_SESSION_ID: ${env:IG_SESSION_ID}
    SENTRY_DSN: ${env:SENTRY_DSN}
    X_DEZGO_KEY: ${env:X_DEZGO_KEY}

package:
  patterns:
    - '!node_modules/**'
    - '!*.ts'

functions:
  cron:
    handler: index.handler
    timeout: 180
    events:
      - schedule:
          rate: rate(1417 minutes)
          enabled: false
