org: freyrsunset
app: fishie
service: fishie
frameworkVersion: "4"
useDotenv: true

provider:
  name: aws
  runtime: nodejs24.x
  environment:
    IG_USERNAME: ${env:IG_USERNAME}
    IG_PASSWORD: ${env:IG_PASSWORD}
    SENTRY_DSN: ${env:SENTRY_DSN}
    X_DEZGO_KEY: ${env:X_DEZGO_KEY}

functions:
  cron:
    handler: index.handler
    timeout: 60 # seconds
    events:
      - schedule:
          rate: rate(1417 minutes)
          enabled: false
