org: freyrsunset
app: fishie
service: fishie
frameworkVersion: "4"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

functions:
  cron:
    handler: index.handler
    timeout: 60 # seconds
    events:
      - schedule: rate(15 minutes)
