org: freyrsunset
app: fishie
service: fishie
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - schedule: rate(15 minutes)
